/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/lisa.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.GLTF_created_0_rootJoint} />
          <skinnedMesh
            geometry={nodes.Object_19.geometry}
            material={materials.shoe}
            skeleton={nodes.Object_19.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_21.geometry}
            material={materials.emotion}
            skeleton={nodes.Object_21.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_11.geometry}
            material={materials.new_face}
            skeleton={nodes.Object_11.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_9.geometry}
            material={materials.eye_white}
            skeleton={nodes.Object_9.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_10.geometry}
            material={materials.skin}
            skeleton={nodes.Object_10.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_15.geometry}
            material={materials.belt}
            skeleton={nodes.Object_15.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_16.geometry}
            material={materials.shoulder_ornament}
            skeleton={nodes.Object_16.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_17.geometry}
            material={materials.cloth}
            skeleton={nodes.Object_17.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_18.geometry}
            material={materials.skirt}
            skeleton={nodes.Object_18.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_20.geometry}
            material={materials.stocking}
            skeleton={nodes.Object_20.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_12.geometry}
            material={materials.hair}
            skeleton={nodes.Object_12.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_13.geometry}
            material={materials.hand_jewel}
            skeleton={nodes.Object_13.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_14.geometry}
            material={materials.material_6}
            skeleton={nodes.Object_14.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_8.geometry}
            material={materials.material}
            skeleton={nodes.Object_8.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/lisa.glb");
